In [61]:
import numpy as np
from matplotlib import pyplot as plt
import math

img = np.arange(0,255,4).reshape((8, 8))
print(img)

[[  0   4   8  12  16  20  24  28]
 [ 32  36  40  44  48  52  56  60]
 [ 64  68  72  76  80  84  88  92]
 [ 96 100 104 108 112 116 120 124]
 [128 132 136 140 144 148 152 156]
 [160 164 168 172 176 180 184 188]
 [192 196 200 204 208 212 216 220]
 [224 228 232 236 240 244 248 252]]


In [62]:
# covariance matrix
np.cov(img, rowvar = False, bias = True)

array([[5376., 5376., 5376., 5376., 5376., 5376., 5376., 5376.],
       [5376., 5376., 5376., 5376., 5376., 5376., 5376., 5376.],
       [5376., 5376., 5376., 5376., 5376., 5376., 5376., 5376.],
       [5376., 5376., 5376., 5376., 5376., 5376., 5376., 5376.],
       [5376., 5376., 5376., 5376., 5376., 5376., 5376., 5376.],
       [5376., 5376., 5376., 5376., 5376., 5376., 5376., 5376.],
       [5376., 5376., 5376., 5376., 5376., 5376., 5376., 5376.],
       [5376., 5376., 5376., 5376., 5376., 5376., 5376., 5376.]])

In [63]:
def correlation(img):
    return np.corrcoef(img, rowvar = False)

In [64]:
def homogeneity(img):
    res = 0
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            res += img[i,j] / (1 + abs(j - i))
    print(res)

In [65]:
def entropy(img):
    res = 0
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            res += img[i,j] * math.log(img[i,j]) # log base 10 or 2?
            #  If pixel value is 0 log is infinite
    return res * -1

In [66]:
def variance(img):
    return np.var(img)

In [67]:
def contrast(img):
    res = 0
    res1 = 0
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            n = math.pow(i-j,2)
            res += img[i,j] * n
    return res

In [68]:
def longRunEmphasis(img):
    pass

In [69]:
def runePercentage(img):
    pass

In [70]:
def var_mtx(img):
    return np.var(img,axis=0), np.var(img,axis=1)